Public Interface IToVector
	Function ToMDecimal() As MDecimal()
	Function ToMDouble() As MDouble()
	Function ToMSingle() As MSingle()
	Function ToMInt8() As MInt8()
	Function ToMInt16() As MInt16()
	Function ToMInt32() As MInt32()
	Function ToMInt64() As MInt64()
	Function ToMUInt8() As MUInt8()
	Function ToMUInt16() As MUInt16()
	Function ToMUInt32() As MUInt32()
	Function ToMUInt64() As MUInt64()
	Function ToDecimal() As Decimal()
	Function ToDouble() As Double()
	Function ToSingle() As Single()
	Function ToSByte() As SByte()
	Function ToShort() As Short()
	Function ToInteger() As Integer()
	Function ToLong() As Long()
	Function ToByte() As Byte()
	Function ToUShort() As UShort()
	Function ToUInteger() As UInteger()
	Function ToULong() As ULong()
End Interface
